# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
emulated_hue:
  host_ip: "192.168.1.76"  # Reemplaza con la IP fija de tu Home Assistant
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - light
    - switch
#  expose_by_default: false
#  entities:
#    light.fer:
#      name: "Fer"
#      hidden: false
