blueprint:
  name: Loginovo ZG-101ZL Switch
  description: Automate the  Loginovo ZG-101ZL Smart button
  domain: automation
  input:
    loginovo_button:
      name: Loginovo  ZG-101ZL Switch
      selector:
        entity:
          integration: mqtt
          domain: sensor
single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  source_url: https://github.com/ferezvi/HA-Blueprints/edit/main/Loginovo_ZG-101Z_Zigbee2mqtt.yaml
mode: restart
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input "loginovo_button"
  attribute: action
action:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions: 
    - "{{ command == 'single' }}"
    sequence: !input "single_press"
  - conditions: 
    - "{{ command == 'double' }}"
    sequence: !input "double_press"
  - conditions: 
    - "{{ command == 'long' }}"
    sequence: !input "long_press"
