blueprint:
  name: Loginovo ZG-101ZL Switch (Zigbee2MQTT)
  description: Automate the ZG-101ZL Smart button
  author: ferezvi
  domain: automation
  source_url: https://github.com/ferezvi/HA-Blueprints/blob/main/Loginovo_ZG-101Z_Zigbee2mqtt.yaml
  input:
    tuya_4button_switch:
      name: Tuya Button Switch
      description: Tuya Button Switch to use
      selector:
        device:
          integration: mqtt
          manufacturer: _TZ3000_ja5osu5g
          model: TS004F
    single_action:
      name: Single Press
      description: Action to run
      default: []
      selector:
        action: {}
    double_action:
      name: Double press
      description: Action to run
      default: []
      selector:
        action: {}
    hold_action:
      name: long press
      description: Action to run
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input action_sensor
condition:
  - condition: template
    value_template: '{{ trigger.to_state.state in ("single","double","hold") }}'
action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input single_action
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input double_action
      - conditions:
          - "{{ command == 'hold' }}"
        sequence: !input hold_action
