blueprint:
  name: 🌅 Luz con Desfase Solar o Hora Fija
  description: Automatización flexible que enciende y apaga luces usando eventos solares (con desfase) o a horas fijas.
  domain: automation
  input:
    light_entity:
      name: Entidad de Luz a Controlar
      description: La luz o grupo de luces que quieres automatizar.
      selector:
        entity:
          domain: light
    
    turn_on_trigger_type:
      name: Tipo de Encendido
      description: ¿Quieres encender al atardecer (sunset) o a una hora específica (time)?
      selector:
        select:
          options:
            - label: Atardecer (Sunset)
              value: sunset
            - label: Hora Fija (Time)
              value: time
          mode: list
          
    sunset_offset:
      name: Desfase para el Atardecer (Encendido)
      description: Desfase opcional para el atardecer. Ejemplo -00:15:00 para antes o 00:20:00 para después.
      default: "00:00:00"
      selector:
        text:
        
    turn_on_time:
      name: Hora Fija de Encendido (Solo si seleccionaste Hora Fija)
      description: Hora a la que la luz se debe encender. Ejemplo 18:30:00
      default: "18:00:00"
      selector:
        time:
    
    turn_off_trigger_type:
      name: Tipo de Apagado
      description: ¿Quieres apagar al amanecer (sunrise) o a una hora específica (time)?
      selector:
        select:
          options:
            - label: Amanecer (Sunrise)
              value: sunrise
            - label: Hora Fija (Time)
              value: time
          mode: list
          
    sunrise_offset:
      name: Desfase para el Amanecer (Apagado)
      description: Desfase opcional para el amanecer. Ejemplo 00:10:00 para después o -00:05:00 para antes.
      default: "00:00:00"
      selector:
        text:
        
    turn_off_time:
      name: Hora Fija de Apagado (Solo si seleccionaste Hora Fija)
      description: Hora a la que la luz se debe apagar. Ejemplo 23:00:00
      default: "23:00:00"
      selector:
        time:

variables:
  turn_on_type: !input turn_on_trigger_type
  turn_off_type: !input turn_off_trigger_type
        
trigger:
  - platform: sun
    event: sunset
    offset: !input sunset_offset
    id: "encendido_atardecer"
    
  - platform: time
    at: !input turn_on_time
    id: "encendido_hora_fija"
    
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
    id: "apagado_amanecer"
    
  - platform: time
    at: !input turn_off_time
    id: "apagado_hora_fija"

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "encendido_atardecer"
                  - condition: template
                    value_template: "{{ turn_on_type == 'sunset' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: "encendido_hora_fija"
                  - condition: template
                    value_template: "{{ turn_on_type == 'time' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
            data: {}
            
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "apagado_amanecer"
                  - condition: template
                    value_template: "{{ turn_off_type == 'sunrise' }}"
              - condition: and
                conditions:
                  - condition: trigger
                    id: "apagado_hora_fija"
                  - condition: template
                    value_template: "{{ turn_off_type == 'time' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
            data: {}
    default: []
    
mode: single
