blueprint:
  name: 🌅 Luz con Desfase Solar o Hora Fija
  description: Automatización flexible que enciende y apaga luces usando eventos solares (con desfase) o a horas fijas.
  domain: automation
  source_url: 
  input:
    light_entity:
      name: Entidad de Luz a Controlar
      description: La luz o grupo de luces que quieres automatizar.
      selector:
        entity:
          domain: light
    
    turn_on_trigger_type:
      name: Tipo de Encendido
      description: ¿Quieres encender al atardecer (sunset) o a una hora específica (time)?
      selector:
        select:
          options:
            - label: Atardecer (Sunset)
              value: sunset
            - label: Hora Fija (Time)
              value: time
          mode: list
          
    sunset_offset:
      name: Desfase para el Atardecer (Encendido)
      # ⚠️ Descripción más corta para evitar el error de YAML
      description: 'Desfase opcional (-HH:MM:SS) para el atardecer. Ej: -00:15:00 antes, 00:20:00 después.'
      default: ""
      selector:
        text:

    turn_on_time:
      name: Hora Fija de Encendido (Solo si seleccionaste Hora Fija)
      description: Hora a la que la luz se debe encender (Ej: 18:30:00).
      default: "18:00:00"
      selector:
        time:
    
    turn_off_trigger_type:
      name: Tipo de Apagado
      description: ¿Quieres apagar al amanecer (sunrise) o a una hora específica (time)?
      selector:
        select:
          options:
            - label: Amanecer (Sunrise)
              value: sunrise
            - label: Hora Fija (Time)
              value: time
          mode: list

    sunrise_offset:
      name: Desfase para el Amanecer (Apagado)
      # ⚠️ Descripción más corta para evitar el error de YAML
      description: 'Desfase opcional (-HH:MM:SS) para el amanecer. Ej: 00:10:00 después, -00:05:00 antes.'
      default: ""
      selector:
        text:

    turn_off_time:
      name: Hora Fija de Apagado (Solo si seleccionaste Hora Fija)
      description: Hora a la que la luz se debe apagar (Ej: 23:00:00).
      default: "23:00:00"
      selector:
        time:
        
trigger:
  - platform: sun
    event: sunset
    offset: !input 'sunset_offset'
    id: "encendido_atardecer"
    
  - platform: time
    at: !input 'turn_on_time'
    id: "encendido_hora_fija"

  - platform: sun
    event: sunrise
    offset: !input 'sunrise_offset'
    id: "apagado_amanecer"
    
  - platform: time
    at: !input 'turn_off_time'
    id: "apagado_hora_fija"

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - '{{ trigger.id == "encendido_atardecer" }}'
                  - '{{ trigger_input.turn_on_trigger_type == "sunset" }}'
              - condition: and
                conditions:
                  - '{{ trigger.id == "encendido_hora_fija" }}'
                  - '{{ trigger_input.turn_on_trigger_type == "time" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input 'light_entity'
            data: {}
            
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - '{{ trigger.id == "apagado_amanecer" }}'
                  - '{{ trigger_input.turn_off_trigger_type == "sunrise" }}'
              - condition: and
                conditions:
                  - '{{ trigger.id == "apagado_hora_fija" }}'
                  - '{{ trigger_input.turn_off_trigger_type == "time" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input 'light_entity'
            data: {}
    default: []
mode: single
